#!/bin/bash

while [[ $# -gt 0 ]]
do
	opt="$1"
	case $opt in
		-f|--file)
			file="$2"
			shift
		;;
		-r|--read)
			cat $file
			shift
		;;
		-h|--help)
			echo -e "
baxar (BAsh Xml pARser) is an XML parser in bash.

	-f|--file	Specify the XML file to parse.
	-h|--help	Display this page.
"
		;;
	esac
	shift
done

bashVersion=$(echo ${BASH_VERSION%%[^0-9.]*} | grep -o ^[0-9]*)

# Create array with syntax based on the following file:
# <xml>
#  <name>
#   John Smith
#  </name>
#  <homes>
#   <parents>
#    1234 main drive
#   </parents>
#   <current>
#    2345 foo lane
#   </currents>
#  </homes>
#  <phone>
#   1235554567
#  </phone>
# </xml>
#
# Array syntax
#
#	xml {
#		[name] => "John Smith"
#		[homes] => {
#			[parents] => 1234 main drive
#			[current] => 2345 foo lane
#		} 
#		[phone] => 1235554567
#	}
